/*
    Copyright (c) 2013 Yaniv Kamay,
    All rights reserved.

    Source code is provided for evaluation purposes only. Modification or use in
    source code for any other purpose is prohibited.

    Binary code (i.e. the binary form of source code form) is allowed to use for
    evaluation purposes only. Modification or use in binary code for any other
    purpose is prohibited.

    Redistribution, in source form or in binary form, with or without modification,
    are not permitted.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTOR BE LIABLE FOR
    ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
    ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
    NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
    IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef _H_NOX
#define _H_NOX

#define NOX_PCI_VENDOR_ID 0x1aaa
#define NOX_PCI_DEV_ID_HOST_BRIDGE 0x0001
#define NOX_PCI_DEV_HOST_BRIDGE_REV 1
#define NOX_ADDRESS_LINES 52

enum {
    PLATFORM_IO_LOCK = 0x00,
    PLATFORM_IO_SELECT = 0x01,
    PLATFORM_IO_LOG = 0x02,
    PLATFORM_IO_PUT_BYTE = 0x03,
    PLATFORM_IO_ERROR = 0x04,
    PLATFORM_IO_REGISTER = 0x08,
    PLATFORM_IO_END = 0x0c,

    PLATFORM_MEM_PAGES = 1,
    PLATFORM_LOG_BUF_SIZE = 1024,
};

enum {
    PLATFORM_REG_BELOW_1M_USED_PAGES,
    PLATFORM_REG_ABOVE_1M_PAGES,
    PLATFORM_REG_BELOW_4G_PAGES,
    PLATFORM_REG_BELOW_4G_USED_PAGES,
    PLATFORM_REG_ABOVE_4G_PAGES,
    PLATFORM_REG_WRITE_POS,
};


#define PLATFORM_ERR_TYPE_SHIFT 29
#define PLATFORM_ERR_SUBSYS_SHIFT 16

#define PLATFORM_MK_ERR(type, subsys, code)                     \
    (((uint32_t)(type) << PLATFORM_ERR_TYPE_SHIFT) |            \
    ((uint32_t)(subsys) << PLATFORM_ERR_SUBSYS_SHIFT) |         \
    (code))


enum {
    PLATFORM_ERR_TYPE_INFO = 1,
    PLATFORM_ERR_TYPE_WARN,
    PLATFORM_ERR_TYPE_ERROR,
};


enum {
    PLATFORM_ERR_SUBSYS_BIOS = 1,
};


#endif

