/*
    Copyright (c) 2013 Yaniv Kamay,
    All rights reserved.

    Source code is provided for evaluation purposes only. Modification or use in
    source code for any other purpose is prohibited.

    Binary code (i.e. the binary form of source code form) is allowed to use for
    evaluation purposes only. Modification or use in binary code for any other
    purpose is prohibited.

    Redistribution, in source form or in binary form, with or without modification,
    are not permitted.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTOR BE LIABLE FOR
    ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
    ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
    NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
    IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef _H_PCI
#define _H_PCI

#define NOX_PCI_VENDOR_ID 0x1aaa

#define NOX_PCI_DEV_ID_HOST_BRIDGE 0x0001
#define NOX_PCI_DEV_ID_ISA_BRIDGE 0x0010
#define NOX_PCI_DEV_ID_VGA 0x0100
#define NOX_PCI_DEV_ID_IDE 0x0110

#define PCI_CLASS_MASS_STORAGE 0x01
#define PCI_MASS_STORAGE_SUBCLASS_IDE 0x01
#define PCI_IDE_PROGIF_BUS_MASTER_BIT 7

#define PCI_CLASS_DISPLAY 0x03
#define PCI_DISPLAY_SUBCLASS_VGA 0x00
#define PCI_VGA_INTERFACE_VGACOMPAT 0x00

#define PCI_CLASS_BRIDGE 0x06
#define PCI_SUBCLASS_BRIDGE_HOST 0x00
#define PCI_SUBCLASS_BRIDGE_ISA 0x01

#define PCI_CLASS_SYSTEM 0x08
#define PCI_SUBCLASS_SYSTEM_OTHER 0x80

enum {
    PCI_CONF_VENDOR = 0x00,
    PCI_CONF_DEVICE = 0x02,
    PCI_CONF_COMMAND = 0x04,
    PCI_CONF_STATUS = 0x06,
    PCI_CONF_REVISION = 0x08,
    PCI_CONF_CLASS = 0x09,
    PCI_CONF_CACHE_LINE = 0x0c,
    PCI_CONF_CACHE_LATENCY = 0x0d,
    PCI_CONF_BAR_0 = 0x10,
    PCI_CONF_BAR_1 = 0x14,
    PCI_CONF_BAR_2 = 0x18,
    PCI_CONF_BAR_3 = 0x1c,
    PCI_CONF_BAR_4 = 0x20,
    PCI_CONF_BAR_5 = 0x24,
    PCI_CONF_SUBSYS_VENDOR = 0x2c,
    PCI_CONF_SUBSYS_ID = 0x2e,
    PCI_CONF_ROM_ADDRESS = 0x30,
    PCI_CONF_INTERRUPT_LINE = 0x3c,
    PCI_CONF_INTERRUPT_PIN = 0x3d,

    PCI_CONF_TYPE_0_SIZE = 0x40,

    PCI_COMMAND_MASK = ~((1 << 7) | ~((1 << 11) - 1)),
    PCI_COMMAND_ENABLE_IO = (1 << 0),
    PCI_COMMAND_ENABLE_MEM = (1 << 1),
    PCI_COMMAND_DISABLE_INTERRUPT = (1 << 10),

    PCI_STATUS_RESET_MASK = (1 << 8) | ~((1 << 11) - 1),
    PCI_STATUS_INTERRUPT_MASK = (1 << 3),
    PCI_STATUS_66MHZ_MASK = (1 << 5),

    PCI_IO_MIN_SIZE = 4,
    PCI_IO_MAX_SIZE = 256,

    PCI_MEM_MIN_SIZE = 16,

    PCI_BAR_IO_MASK = (1 << 0),
    PCI_BAR_PREFATCH_MASK = (1 << 3),
    PCI_BAR_MEM_TYPE_64BITS = 2,
    PCI_BAR_MEM_TYPE_SHIFT = 1,

    PCI_ROM_MAX_SIZE = 16 * MB,
    PCI_ROM_MIN_SIZE = GUEST_PAGE_SIZE, // PCI spec min is (1 << 11)
    PCI_ROM_ENABLE_MASK = 0x1,
    PCI_ROM_FIRST_ADDRESS_BIT = 11,
    PCI_ROM_ADDRESS_MASK = ~((1 << PCI_ROM_FIRST_ADDRESS_BIT) - 1),
    PCI_ROM_MASK = PCI_ROM_ADDRESS_MASK | PCI_ROM_ENABLE_MASK,

    PCI_INTTERUPT_PIN_A = 1,
    PCI_INTTERUPT_PIN_B,
    PCI_INTTERUPT_PIN_C,
    PCI_INTTERUPT_PIN_D,
};

#endif

